using System;
using System.Collections.Generic;
using System.Linq;
using NexGenSales.Models;
using NexGenSales.Services.Data.Repository;

namespace NexGenSales.Core
{
    /// <summary>
    /// Serves as the primary data aggregation layer for the Analytics Dashboard.
    /// Fetches raw sales records from the SQLite database and performs in-memory 
    /// LINQ queries to generate metrics based on a specified date range.
    /// </summary>
    public class DataRepository
    {
        private readonly DateTime _startDate;
        private readonly List<SalesRecord> _filteredSales;

        /// <summary>
        /// Initializes the repository, fetches all sales records, and filters them 
        /// to include only transactions that occurred on or after the specified start date.
        /// </summary>
        /// <param name="startDate">The beginning of the date range for data analysis.</param>
        public DataRepository(DateTime startDate)
        {
            _startDate = startDate;

            // Initialize database service and fetch all available records
            var salesRepo = new SalesRecordRepository(new SqliteService());
            var allSales = salesRepo.GetAll().GetAwaiter().GetResult() ?? new List<SalesRecord>();

            // Apply in-memory time-series filtering
            _filteredSales = allSales.Where(s => s.Date_Time >= _startDate).ToList();
        }

        /// <summary>
        /// Checks if there are any sales records available for the selected date range.
        /// </summary>
        public bool HasData => _filteredSales != null && _filteredSales.Any();

        /// <summary>
        /// Calculates the profit margin ratio for each supplier and identifies those 
        /// falling below the acceptable 20% threshold.
        /// </summary>
        /// <returns>Tuple containing Supplier IDs, Profit Ratios, and Low Margin alert flags.</returns>
        public (string[] Suppliers, double[] ProfitRatios, bool[] IsLowMargin) GetSupplierProfitabilityData()
        {
            Console.WriteLine("[DataRepository] LINQ: Calculating Supplier Profitability...");

            // Safeguard against empty data sets to prevent UI crashes
            if (_filteredSales == null || !_filteredSales.Any())
                return (Array.Empty<string>(), Array.Empty<double>(), Array.Empty<bool>());

            var supplierGroups = _filteredSales
                .GroupBy(s => s.Supplier_ID)
                .Select(g => {
                    double totalRevenue = g.Sum(s => s.Net_Revenue);
                    double totalCost = g.Sum(s => s.Quantity_Sold * s.Unit_Purchase_Cost);

                    // Prevent division by zero; calculate standard profit margin
                    double ratio = totalRevenue > 0 ? (totalRevenue - totalCost) / totalRevenue : 0;

                    return new
                    {
                        Supplier = g.Key,
                        ProfitRatio = ratio,
                        IsLow = ratio < 0.20 // Flag true if margin is below 20%
                    };
                }).ToList();

            return (supplierGroups.Select(x => x.Supplier).ToArray(),
                    supplierGroups.Select(x => x.ProfitRatio).ToArray(),
                    supplierGroups.Select(x => x.IsLow).ToArray());
        }

        /// <summary>
        /// Identifies the top 10 fastest-moving items based on total quantity sold.
        /// </summary>
        /// <returns>Tuple containing Item IDs and their total sales quantities.</returns>
        public (string[] Items, int[] QuantitiesSold) GetItemVelocityData()
        {
            Console.WriteLine("[DataRepository] LINQ: Calculating Item Velocity...");

            // Return empty arrays if no data is available for the selected period
            if (_filteredSales == null || !_filteredSales.Any())
                return (Array.Empty<string>(), Array.Empty<int>());

            var velocityGroups = _filteredSales
                .GroupBy(s => s.Item_ID)
                .Select(g => new {
                    ItemId = g.Key,
                    TotalQty = (int)g.Sum(s => s.Quantity_Sold)
                })
                .OrderByDescending(x => x.TotalQty)
                .Take(10) // Restrict to top 10 best-sellers
                .ToList();

            return (velocityGroups.Select(x => x.ItemId).ToArray(),
                    velocityGroups.Select(x => x.TotalQty).ToArray());
        }

        /// <summary>
        /// Calculates the average daily revenue generated by the top 5 performing items.
        /// </summary>
        /// <returns>Tuple containing Item IDs and their daily average revenue.</returns>
        public (string[] Items, double[] AvgDailyRevenue) GetRevenueContributionData()
        {
            Console.WriteLine("[DataRepository] LINQ: Calculating Revenue Contribution...");

            if (_filteredSales == null || !_filteredSales.Any())
                return (Array.Empty<string>(), Array.Empty<double>());

            // Calculate total days in the selected range (minimum 1 to avoid division by zero)
            double totalDays = (DateTime.Today - _startDate).TotalDays;
            if (totalDays < 1) totalDays = 1;

            var revenueGroups = _filteredSales
                .GroupBy(s => s.Item_ID)
                .Select(g => new {
                    ItemId = g.Key,
                    AvgRev = g.Sum(s => s.Net_Revenue) / totalDays
                })
                .OrderByDescending(x => x.AvgRev)
                .Take(5) // Restrict to top 5 revenue generators
                .ToList();

            return (revenueGroups.Select(x => x.ItemId).ToArray(),
                    revenueGroups.Select(x => x.AvgRev).ToArray());
        }

        /// <summary>
        /// Aggregates net revenue on a daily basis to map the sales trend over time.
        /// </summary>
        /// <returns>Tuple containing Day labels (e.g., "Monday") and corresponding total revenues.</returns>
        public (string[] Days, double[] TotalRevenue) GetTrendAnalysisData()
        {
            Console.WriteLine("[DataRepository] LINQ: Calculating Trend Analysis...");

            if (_filteredSales == null || !_filteredSales.Any())
                return (Array.Empty<string>(), Array.Empty<double>());

            var trendGroups = _filteredSales
                .GroupBy(s => s.Date_Time.Date)
                .OrderBy(g => g.Key)
                .Select(g => new {
                    DayLabel = g.Key.ToString("dddd"), // Formats output to full day name (e.g., "Monday")
                    DailyTotal = (double)g.Sum(s => s.Net_Revenue) // Explicit cast required for LiveCharts integration
                }).ToList();

            return (trendGroups.Select(x => x.DayLabel).ToArray(),
                    trendGroups.Select(x => x.DailyTotal).ToArray());
        }

        /// <summary>
        /// Evaluates overall profitability grouped by the allowed discount tiers.
        /// Used to determine which discount strategies yield the highest net return.
        /// </summary>
        /// <returns>Tuple containing Discount Labels and Profitability Scores.</returns>
        public (string[] Labels, double[] Scores) GetDiscountEffectivenessData()
        {
            Console.WriteLine("[DataRepository] LINQ: Calculating Discount Effectiveness...");

            if (_filteredSales == null || !_filteredSales.Any())
                return (Array.Empty<string>(), Array.Empty<double>());

            var discountGroups = _filteredSales
                .GroupBy(s => s.Allowed_Discount)
                .OrderBy(g => g.Key)
                .Select(g => new {
                    DiscountLabel = $"Rs. {g.Key:0.00}",
                    ProfitScore = g.Sum(s => s.Net_Revenue - (s.Quantity_Sold * s.Unit_Purchase_Cost))
                }).ToList();

            return (discountGroups.Select(x => x.DiscountLabel).ToArray(),
                    discountGroups.Select(x => x.ProfitScore).ToArray());
        }
    }
}