using System;
using System.Collections.Generic;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace NexGenSales.Core
{
    public class ReportBuilder
    {
        // Internal interface to hold our modular blocks
        private interface IReportBlock { }
        private class TitleBlock : IReportBlock { public required string Text { get; set; } }
        private class TextBlock : IReportBlock { public required string Text { get; set; } }
        private class ImageBlock : IReportBlock { public required byte[] ImageData { get; set; } }

        private readonly List<IReportBlock> _blocks = new List<IReportBlock>();
        private readonly string _documentTitle;

        public ReportBuilder(string documentTitle = "NexGenSales Executive Report")
        {
            // QuestPDF requires a license declaration. Community is free for SMEs.
            QuestPDF.Settings.License = LicenseType.Community;
            _documentTitle = documentTitle;
        }

        // --- Fluent Methods to Add Blocks ---

        public ReportBuilder AddTitle(string title)
        {
            _blocks.Add(new TitleBlock { Text = title });
            return this;
        }

        public ReportBuilder AddDescription(string text)
        {
            _blocks.Add(new TextBlock { Text = text });
            return this;
        }

        public ReportBuilder AddGraph(byte[] chartImageData)
        {
            if (chartImageData != null && chartImageData.Length > 0)
            {
                _blocks.Add(new ImageBlock { ImageData = chartImageData });
            }
            return this;
        }

        // --- The Final Compilation Method ---

        /// <summary>
        /// Compiles the added blocks and generates the physical PDF file.
        /// </summary>
        public void Generate(string outputPath)
        {
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(11).FontFamily(Fonts.Arial));

                    // Header
                    page.Header().Text(_documentTitle)
                        .SemiBold().FontSize(20).FontColor(Colors.Blue.Darken2);

                    // Content Core (Loops through our modular blocks)
                    page.Content().PaddingVertical(1, Unit.Centimetre).Column(column =>
                    {
                        column.Spacing(15); // Space between blocks

                        foreach (var block in _blocks)
                        {
                            if (block is TitleBlock title)
                            {
                                column.Item().Text(title.Text).FontSize(16).Bold().FontColor(Colors.Grey.Darken3);
                            }
                            else if (block is TextBlock textBlock)
                            {
                                column.Item().Text(textBlock.Text).LineHeight(1.2f);
                            }
                            else if (block is ImageBlock image)
                            {
                                // Adds the captured WPF byte array directly into the PDF layout
                                column.Item().Image(image.ImageData);
                            }
                        }
                    });

                    // Footer
                    page.Footer().AlignCenter().Text(x => 
                    {
                        x.Span("Generated by NexGenSales | Page ");
                        x.CurrentPageNumber();
                    });
                });
            })
            .GeneratePdf(outputPath);
        }
    }
}