using System;

namespace NexGenSales.Models
{
    public class ExpenseRecord
    {
        public int Expense_ID { get; set; } // Auto-generated by SQLite
        public DateTime Date_Recorded { get; set; }
        public required string Expense_Category { get; set; }
        public required string Specific_Type { get; set; }
        public required double Amount { get; set; }
        public string? Asset_ID { get; set; } // Can be null if the expense isn't tied to an asset
    }
}