using System;

namespace NexGenSales.Models
{
    public class ExpensesRecord : BaseModel
    {
        public int Expense_ID { get; set; } // Auto-generated by SQLite
        public DateTime Date_Recorded { get; set; }
        public  string Expense_Category { get; set; }
        public  string Specific_Type { get; set; }
        public  double Amount { get; set; }
        public string Asset_ID { get; set; } // Can be null if the expense isn't tied to an asset
    }
}