using System;

namespace NexGenSales.Models
{
    public class SalesRecord
    {
        public int Transaction_ID { get; set; } // Auto-generated by SQLite
        public DateTime Date_Time { get; set; }
        public required string Item_ID { get; set; }
        public required string Supplier_ID { get; set; }
        public double Quantity_Sold { get; set; }
        public double Unit_Purchase_Cost { get; set; }
        public double Unit_Sale_Price { get; set; }
        public double Allowed_Discounts { get; set; }
        public double Net_Revenue { get; set; }
        public double Current_Stock { get; set; }
    }
}