using System;

namespace NexGenSales.Models
{
    public class SalesRecord : BaseModel
    {
        public int Transaction_ID { get; set; } // Auto-generated by SQLite
        public DateTime Date_Time { get; set; }
        public string Item_ID { get; set; }
        public string Supplier_ID { get; set; }
        public double Quantity_Sold { get; set; }
        public double Unit_Purchase_Cost { get; set; }
        public double Unit_Sale_Price { get; set; }
        public double Allowed_Discount { get; set; }
        public double Net_Revenue { get; set; }
        public double Current_Stock { get; set; }
    }
}